### ISSUE TITLE
Support for mtl 2.1?

### ISSUE THREAD

**Issue by peti** [alephcloud/hs-configuration-tools#38]
GHC 7.8.x ships `transformers-0.3.x` as a core library, which means that users of that compiler cannot update to version 0.4.x without risking conflicts and weird crashes when binaries reference both the core and the non-core variant of `transformers` at the same time. This means that `mtl-2.2.x` cannot be used with GHC 7.8.x. Would you consider changing your package to depend on `mtl-compat` and/or `transformers-compat` instead of the "real" libraries directly to offer transparent support for older versions?

**Comment by larskuhtz** [comment]
Version 0.2.12 does support transformers-0.3.0.0 through transformers-compat and mtl-compat.
