### ISSUE TITLE
configuration-tools-0.2.12 test suite failure

### ISSUE THREAD

**Issue by peti** [alephcloud/hs-configuration-tools#40]
The error messages seems quite extensive; please see http://hydra.cryp.to/build/578312/log/raw for a complete build log.

**Comment by larskuhtz** [comment]
Thanks for the report, I'll take a look.

**Comment by larskuhtz** [comment]
These are the failures in above test results:

```
WARNING: test tlsUrl-4 failed
WARNING: test tlsUrl-6 failed
WARNING: test tlsUrl-4 failed
WARNING: test tlsUrl-6 failed
```

**Comment by bennofs** [comment]
These tests require networking (access to localhost at least). I don't think they will ever work in the  nix sandbox.

**Comment by bennofs** [comment]
Ok I've investigated a little more and the issue is that `getent protocols` fails in the Nix sandbox. This issue is nothing that can be fixed in hs-configuration-tools, it is a Nix issue.
