### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriel439** [alephcloud/hs-configuration-tools#42]
`errors-2.0` will be switching to use `ExceptT` instead of `EitherT`.  If that will break your package, then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by larskuhtz** [comment]
Solved in PR #46.

@Gabriel439 thanks for the notice. I wonder if it would have been even better to motivate package maintainer to actually update their packages to support errors >= 2.0 instead of adding an upper bound. Thanks.

**Comment by Gabriel439** [comment]
I can't upload `errors-2.0` to Hackage yet because it would break a lot of packages without upper bounds.  Once I upload `errors` then I'll be submitting pull requests to upgrade them to use `errors-2.0`.

**Comment by larskuhtz** [comment]
@Gabriel439, wow, that's even better. Thanks for the `errors` package and doing this kind of work!

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by jonsterling** [comment]
Cheers, @Gabriel439! You do a wonderful job nurturing the ecosystem around your packages.

**Comment by Gabriel439** [comment]
@jonsterling Thanks!  I appreciate that :)

**Comment by Gabriel439** [comment]
Oh, also don't forget to upload this to Hackage when you get the chance.  There is no hurry as I'm still a few weeks out before uploading `errors-2.0` to Hackage

**Comment by Gabriel439** [comment]
Just another reminder to upload this to Hackage when you get the chance.  I'm about a week away from releasing `errors-2.0`
