### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by axman6** [alephcloud/hs-configuration-tools#52]
It'd be great to see this on stackage, not much more to say.

**Comment by larskuhtz** [comment]
Done (https://github.com/fpco/stackage/commit/ba9c041744b8f6af9a5ff613676558993508ec73).

Thanks for proposing this!

**Comment by axman6** [comment]
Fantastic, thanks Lars! Also I notice you're responsible for was-cors, which we also use, so thanks for that!
