### ISSUE TITLE
Documentation for updatePorperty doesn't show how to use it

### ISSUE THREAD

**Issue by axman6** [alephcloud/hs-configuration-tools#59]
The code snipped attached to the docs for [updateProperty](https://hackage.haskell.org/package/configuration-tools-0.3.0/docs/Configuration-Utils-ConfigFile.html#v:updateProperty) don't actually show its usage, and it makes no mention of the `%.:` operator which is actually used - it would be good to make this snippet a) use the function and b) reference its infix version.

**Comment by larskuhtz** [comment]
Thanks for reporting this. It's now fixed in master.

**Comment by axman6** [comment]
Thanks Lars!
